# Generated by Django 4.0.6 on 2022-08-25 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Black',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=2500, null=True)),
                ('alcohol_volume', models.FloatField(blank=True, max_length=2, null=True)),
                ('IBU', models.FloatField(blank=True, max_length=2, null=True)),
                ('price', models.FloatField(blank=True, default=True, null=True)),
                ('creation_date', models.DateField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blonde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=2500, null=True)),
                ('alcohol_volume', models.FloatField(blank=True, max_length=2, null=True)),
                ('IBU', models.FloatField(blank=True, max_length=2, null=True)),
                ('price', models.FloatField(blank=True, default=True, null=True)),
                ('creation_date', models.DateField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Red',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=2500, null=True)),
                ('alcohol_volume', models.FloatField(blank=True, max_length=2, null=True)),
                ('IBU', models.FloatField(blank=True, max_length=2, null=True)),
                ('price', models.FloatField(blank=True, default=True, null=True)),
                ('creation_date', models.DateField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
