# Generated by Django 4.0.6 on 2022-08-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cervezas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cerveza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('alcohol_volume', models.FloatField()),
                ('IBU', models.FloatField()),
                ('price', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='Cervezas/')),
            ],
            options={
                'verbose_name': 'Cerveza',
                'verbose_name_plural': 'Cervezas',
            },
        ),
        migrations.DeleteModel(
            name='Black',
        ),
        migrations.DeleteModel(
            name='Blonde',
        ),
        migrations.DeleteModel(
            name='Red',
        ),
    ]
