# Generated by Django 4.0.6 on 2022-09-01 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cervezas', '0003_rename_name_category_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='cerveza',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
